---
- hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: leer log
      command: cat /home/eczepedah/log.txt
      register: contenido_log
       
    - name: lineas de interes
      set_fact:
        lineas_interes: "{{ contenido_log.stdout_lines | select('regex_search', 'FAILED!' | list) }}"    
      
    - name: ver resultado
      debug:
        msg: "{{ lineas_interes }}"

...