---
- hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: filtrar fail
      lineinfile:
        path: /home/eczepedah/log.txt
        regexp: "FAILED!"
        state: present
      register: resultado_filtrado
      
    - name: ver resultado
      debug:
        var: resultado_filtrado

...